env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'semistandard'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
    "indent": ["error", 4],
    "object-curly-newline": ["error", {
        "ObjectPattern": { "multiline": true },
        "ImportDeclaration": "never",
        "ExportDeclaration": { "multiline": true, "minProperties": 3 }
    }]
}
